export const LOAD_SCHOOLS_SUCCESS = "LOAD_SCHOOLS_SUCCESS";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_CURRENT_SCHOOL = "SET_CURRENT_SCHOOL";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
