export const LOAD_SCHOOLS_SUCCESS = "LOAD_SCHOOLS_SUCCESS";
export const SET_LOCATION = "SET_LOCATION";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
